import assert from "node:assert/strict";
import test from "node:test";
import {
  buildIssueDraft,
  handleIssueDrafts,
  parseFollowUpsFromText,
  __testing
} from "../lib/issue-drafts.js";

test("parses issue command intent", () => {
  assert.deepEqual(__testing.parseIssueCommandIntent(""), {
    action: "draft",
    targets: ["github", "linear"],
    create: false,
    text: ""
  });
  assert.deepEqual(__testing.parseIssueCommandIntent("github create ship it"), {
    action: "draft",
    targets: ["github"],
    create: true,
    text: "ship it"
  });
  assert.deepEqual(__testing.parseIssueCommandIntent("linear fix docs"), {
    action: "draft",
    targets: ["linear"],
    create: false,
    text: "fix docs"
  });
});

test("builds GitHub issue draft payload from follow-up", () => {
  const draft = buildIssueDraft(
    "github",
    {
      task: "Ship launch checklist",
      assigneeUserId: "U123",
      dueAt: "2026-07-01T20:00:00.000Z",
      source: "Alex asked for it"
    },
    {
      ownerUserId: "U999",
      channel: "C123",
      threadTs: "1000.000",
      sourceTs: "1000.001",
      mentionedChannels: []
    },
    { NOBO_GITHUB_LABELS: "slack, follow-up" }
  );

  assert.equal(draft.title, "Ship launch checklist");
  assert.deepEqual(draft.payload, {
    title: "Ship launch checklist",
    body: [
      "Generated by NoBo from a Slack thread follow-up.",
      "",
      "Follow-up: Ship launch checklist",
      "Slack assignee: <@U123>",
      "Due: 2026-07-01T20:00:00.000Z",
      "Source: Alex asked for it",
      "",
      "Slack channel: C123",
      "Slack thread: 1000.000"
    ].join("\n"),
    labels: ["slack", "follow-up"]
  });
});

test("formats actionable drafts when create config is absent", async () => {
  const text = await handleIssueDrafts(
    [{ task: "Patch flaky deploy check" }],
    { targets: ["github"], create: true, env: {} }
  );

  assert.match(text, /Couldn't create GitHub issue/);
  assert.match(text, /NOBO_GITHUB_TOKEN or GITHUB_TOKEN/);
  assert.match(text, /Patch flaky deploy check/);
  assert.match(text, /```json/);
});

test("creates GitHub issues when config is present", async () => {
  const requests: Array<{ url: string; body: unknown }> = [];
  const mockFetch = async (url: string | URL | Request, init?: RequestInit) => {
    requests.push({
      url: String(url),
      body: JSON.parse(String(init?.body))
    });
    return new Response(JSON.stringify({ html_url: "https://github.com/acme/nobo/issues/1" }), {
      status: 201
    });
  };

  const text = await handleIssueDrafts(
    [{ task: "Create rollout issue" }],
    {
      targets: ["github"],
      create: true,
      env: {
        NOBO_GITHUB_TOKEN: "secret",
        NOBO_GITHUB_REPOSITORY: "acme/nobo"
      },
      fetch: mockFetch as typeof fetch
    }
  );

  assert.equal(requests.length, 1);
  assert.equal(requests[0]?.url, "https://api.github.com/repos/acme/nobo/issues");
  assert.deepEqual(requests[0]?.body, {
    title: "Create rollout issue",
    body: "Generated by NoBo from a Slack thread follow-up.\n\nFollow-up: Create rollout issue",
    labels: []
  });
  assert.match(text, /Created GitHub issue/);
  assert.match(text, /https:\/\/github.com\/acme\/nobo\/issues\/1/);
});

test("parses pasted slash command follow-up bullets", () => {
  assert.deepEqual(parseFollowUpsFromText("- Fix auth callback\n2. Update docs"), [
    { task: "Fix auth callback" },
    { task: "Update docs" }
  ]);
});
